### ISSUE TITLE
Ex 1.10

### ISSUE THREAD

**Issue by jaaack-wang** [sgignoux/sicp-solutions.net#9]
Both g(n) and h(n) should be piecewise functions where 

- g(n) = 2 ^ n (when n > 0); 0 (when n = 0);
- h(n) = 2 ^ h(n-1) (when n > 1); 2 (when n = 1); 0 (when n = 0)

**Comment by sgignoux** [comment]
Hello, thanks to both of you for comments.

@jaaack-wang Because 2^0 = 1  (you can find many proof of that online) and 2^1 = 2, there is no need to add the cases you suggest.

@chtnnh When you ask "what is the value of h you are plugging in", you mean in $h(n) = 2^{h(n-1)}$ ? In that case $h$ is just the function that is defined. This is a recursive definition. 

The solution can't be 2^(2^n): if you check with n=2, your solution would be 2^(2^2)=16, but if you run the computation you can see the `(h 2)` = 4. Interestingly 2^(2^2)=(h 4)=65536, but for larger and smaller value the result doesn't match. 

I have added a more detailed explanation for the solution.
